version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
#    networks:
#      hostnet: {}
    network_mode: host

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_CREATE_TOPICS=users:1:1,orders:1:1,zipkin:1:1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper
#    networks:
#      hostnet: {}
    network_mode: host

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
#    networks:
#      hostnet: {}
    network_mode: host

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    depends_on:
      - kafka
    environment:
      - "KAFKA_BOOTSTRAP_SERVERS=localhost:9092"
    ports:
      - "9411:9411"
#    networks:
#      hostnet: {}
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-local.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
#    networks:
#      hostnet: {}
    network_mode: host

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    container_name: grafana
#    networks:
#      hostnet: {}
    network_mode: host

#networks:
#  hostnet:
#    external: true
#    name: host

