server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
  boot:
    admin:
      client:
        url: http://localhost:8089

  zipkin:
    baseUrl: http://localhost:9411
    sender.type: web
  sleuth.sampler.percentage: 1

logging:
  level:
    root: INFO
    liquibase: WARN
    wombatukun: DEBUG

auth:
  signing-key: '{cipher}455d952fd23bcadf31fe76b2fbede0ac1a25cbe0fb179c9fa2a2c8b36a2ebfc4a345db1b91000109dbe47e0f1eb776c08b15fab2d4367492116286633d9da3a5'

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"