eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8082/eureka/

spring:
  boot:
    admin:
      client:
        url: http://adminserver:8089

  redis:
    host: redis
    port: 6379

  zipkin:
    baseUrl: http://zipkin:9411