spring:
  jpa:
    show-sql: false

  datasource:
    url: 'jdbc:postgresql://database:5432/delivery_orders'
    username: postgres
    password: '{cipher}34964d42d5eb2434cb7c072cbc80a311ee718f7836e8f6c1dfe38a2358865267'

  boot:
    admin:
      client:
        url: http://adminserver:8089

  kafka:
    bootstrap-servers:
      - kafka:9092

  zipkin:
    baseUrl: http://zipkin:9411

redis:
  host: redis
  port: 6379

auth:
  instance: http://auth-service:8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8082/eureka/